name: Run command

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command to run"
        required: true
        type: string
      commit_msg:
        description: "Commit Message"
        required: true
        type: string

jobs:
  run_command:
    name: Running command
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with: 
        ref: "vercel"
    - name: Run command
      run: ${{ inputs.command }}
    - name: Push changes to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -u
        git reset -- node_modules
        git commit -m "${{ inputs.commit_msg }}"
        git push origin vercel
